language: ruby
os: linux
dist: xenial

services:
- docker

before_install:
- bash ./.travis-build.sh 1

script:
- bash ./.travis-build.sh
- bash  ./.travis-build.sh 2

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_API
  file: "./builder/builds/OnlyKey.cpp.hex"
  skip_cleanup: true
  on:
    branch: build
    tags: true
