language: ruby
os: linux
dist: xenial

services:
  - docker
  
before_install:
- bash ./.travis-build.sh 1

script:
- bash ./.travis-build.sh

jobs:
  include:
    - stage: build
      script: 
      - ./.travis-build.sh
    - stage: export
      script: 
      - ./.travis-build.sh 2